baseurl: "https://www.evovanialeonard.co.za"

title      : evo Vania Leonard - Bond Origination & Home Loans Expert in Gqeberha Port Elizabeth PE
email      : vania.leonard@evogroup.co.za
description: Contact evo Vania Leonard from Gqeberha, Port Elizabeth to help you with home loan. Vania is a seasoned property professional in mortgages and property finance with 28 years of experience. Vania's experience ranges from sales to finance and she specializes in bonds, homeloans and origination. Vania is committed to excellent client service, building long-term relationships..
author     : Eben Roux / Pieter Oosthuizen

analytics:
  google: G-Z72P29Y4YF

collections:
  portfolio:

markdown: kramdown

webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD

logo:
  path: /assets/logo.png

exclude: [node_modules,webpack-config.js,package.json,package-lock.json]